import React, { useState } from 'react';
import {
  Bell,
  GraduationCap,
  Calendar,
  LogOut,
  Shield,
  Clock,
  Menu,
} from 'lucide-react';
import { useApp } from '../context/AppContext';

interface HeaderProps {
  mobileOpen?: boolean;
  setMobileOpen?: (open: boolean) => void;
}

export const Header: React.FC<HeaderProps> = ({ mobileOpen, setMobileOpen }) => {
  const {
    currentUser,
    logout,
    isSuperAdminPortal
  } = useApp();

  const [showNotifications, setShowNotifications] = useState(false);

  const notifications = [
    {
      id: 'n1',
      title: 'Question Paper Generated & Ready for Review',
      sub: '24CS301 - Computer Organization IA-1 generated by Exam Cell engine',
      time: '10 mins ago',
      unread: true,
    },
    {
      id: 'n2',
      title: 'End Semester Paper Approved',
      sub: '24AM411 - Artificial Intelligence End Semester paper sealed by COE',
      time: '1 hour ago',
      unread: false,
    },
    {
      id: 'n3',
      title: 'Question Bank Threshold Met',
      sub: 'AIDS Department has added over 90 approved questions for Unit I–V',
      time: 'Yesterday',
      unread: false,
    }
  ];

  return (
    <header className="sticky top-0 z-30 flex h-16 w-full items-center justify-between border-b border-[#E5E7EB] bg-white px-4 md:px-8 shadow-[0_1px_3px_rgba(0,0,0,0.03)]">
      {/* Left: Branding & Mobile menu */}
      <div className="flex items-center gap-3">
        {setMobileOpen && (
          <button
            type="button"
            onClick={() => setMobileOpen(!mobileOpen)}
            className="lg:hidden flex h-9 w-9 items-center justify-center rounded-xl border border-[#E5E7EB] text-[#111827] hover:bg-[#F7F8FA] active:scale-95 transition-all cursor-pointer"
            aria-label="Toggle navigation menu"
          >
            <Menu className="h-5 w-5" />
          </button>
        )}
        <div className={`flex h-10 w-10 items-center justify-center rounded-xl text-white shadow-sm ${isSuperAdminPortal ? 'bg-purple-700' : 'bg-[#D71945]'}`}>
          <GraduationCap className="h-6 w-6" />
        </div>
        <div>
          <div className="flex items-center gap-2">
            <span className="text-lg font-extrabold tracking-tight text-[#111827]">
              MSAJCE
            </span>
            <span className="hidden sm:inline-flex items-center gap-1 rounded-full bg-[#EAF3FF] px-2.5 py-0.5 text-[11px] font-semibold text-[#1976D2]">
              <Shield className="h-3 w-3" /> Autonomous
            </span>
          </div>
          <div className={`text-[11px] font-semibold tracking-wider uppercase ${isSuperAdminPortal ? 'text-purple-700' : 'text-[#D71945]'}`}>
            {isSuperAdminPortal ? 'Super Admin Portal' : 'Academic Systems'}
          </div>
        </div>
      </div>

      {/* Right Controls */}
      <div className="flex items-center gap-3 md:gap-4">
        {/* Academic Year Banner (Exam Cell only) */}
        {!isSuperAdminPortal && (
          <div className="hidden lg:flex items-center gap-2 rounded-xl border border-[#E5E7EB] bg-[#F7F8FA] px-3 py-1.5 text-xs text-[#64748B]">
            <Calendar className="h-3.5 w-3.5 text-[#1976D2]" />
            <span>Academic Year:</span>
            <span className="font-semibold text-[#111827]">2024–2025 (Even Semester)</span>
          </div>
        )}

        {/* Portal indicator pill */}
        <div className="hidden sm:flex items-center gap-1.5 rounded-xl border border-[#E5E7EB] bg-[#F7F8FA] px-3 py-1.5">
          {isSuperAdminPortal ? (
            <span className="flex items-center gap-1 text-[11px] font-extrabold text-purple-700">
              Super Admin
            </span>
          ) : (
            <span className="flex items-center gap-1 text-[11px] font-extrabold text-[#B45309]">
              Exam Cell Portal
            </span>
          )}
        </div>

        {/* Notifications */}
        <div className="relative">
          <button
            onClick={() => setShowNotifications(!showNotifications)}
            className="relative flex h-9 w-9 items-center justify-center rounded-xl border border-[#E5E7EB] text-[#64748B] hover:bg-[#F7F8FA] hover:text-[#111827] transition-colors"
            aria-label="View notifications"
          >
            <Bell className="h-4 w-4" />
            <span className="absolute top-1.5 right-1.5 h-2 w-2 rounded-full bg-[#D71945] ring-2 ring-white" />
          </button>

          {showNotifications && (
            <div className="absolute right-0 mt-2 w-80 sm:w-96 rounded-2xl border border-[#E5E7EB] bg-white p-3 shadow-xl z-50">
              <div className="flex items-center justify-between border-b border-[#E5E7EB] pb-2.5 px-1">
                <span className="text-xs font-bold uppercase tracking-wider text-[#111827]">
                  Academic Notifications
                </span>
                <span className="rounded-full bg-[#FFF0F3] px-2 py-0.5 text-[10px] font-semibold text-[#D71945]">
                  1 New
                </span>
              </div>
              <div className="mt-2 divide-y divide-[#F1F5F9] max-h-72 overflow-y-auto">
                {notifications.map((item) => (
                  <div key={item.id} className="py-2.5 px-2 hover:bg-[#F7F8FA] rounded-xl transition-colors cursor-pointer">
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-xs font-semibold text-[#111827]">{item.title}</p>
                      {item.unread && <span className="h-1.5 w-1.5 rounded-full bg-[#D71945] shrink-0 mt-1" />}
                    </div>
                    <p className="mt-1 text-[11px] text-[#64748B] leading-relaxed">{item.sub}</p>
                    <span className="mt-1.5 inline-flex items-center gap-1 text-[10px] text-[#94A3B8]">
                      <Clock className="h-3 w-3" /> {item.time}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* User Avatar & Logout */}
        <div className="flex items-center gap-2 pl-1 border-l border-[#E5E7EB]">
          <div className={`flex h-9 w-9 items-center justify-center rounded-xl text-xs font-bold text-white shadow-sm ${isSuperAdminPortal ? 'bg-purple-700' : 'bg-[#111827]'}`}>
            {(currentUser?.name || 'Staff User').split(' ').filter(Boolean).map(n => n[0]).slice(0, 2).join('') || 'U'}
          </div>
          <div className="hidden md:block text-left">
            <div className="text-xs font-bold text-[#111827] line-clamp-1 leading-tight">{currentUser?.name || 'Staff User'}</div>
            <div className="text-[10px] font-medium text-[#64748B]">{currentUser?.email || ''}</div>
          </div>
          <button
            onClick={logout}
            className="ml-1 p-2 text-[#94A3B8] hover:text-[#D71945] transition-colors"
            title="Sign Out"
          >
            <LogOut className="h-4 w-4" />
          </button>
        </div>
      </div>
    </header>
  );
};
